# https://github.com/actions/cache
# https://github.com/actions/checkout
# https://github.com/ncipollo/release-action
# https://docs.github.com/actions/using-workflows
# https://docs.github.com/actions/learn-github-actions/contexts

name: GitHub Continuous Integration

on: [push, pull_request]

env:
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') && github.repository == 'jakwings/GoodbyeBigSlow.kext' }}
  VERSION_MIN: '10.11'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Reuse cached files
        uses: actions/cache@v2
        with:
          path: ~/Thirdparty
          key: ${{ runner.os }}-${{ env.VERSION_MIN }}

      - name: Download MacOS SDK
        run: |
          dir='/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform'
          sudo /usr/libexec/PlistBuddy -c "set :MinimumSDKVersion ${VERSION_MIN}" "${dir}/Info.plist"
          if ! [ -e ~/Thirdparty/sdk.tar.xz ]; then
            mkdir -p ~/Thirdparty
            curl --fail -L -o ~/Thirdparty/sdk.tar.xz "https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX${VERSION_MIN}.sdk.tar.xz"
          fi
          tar xzf ~/Thirdparty/sdk.tar.xz -C "${dir}/Developer/SDKs/"

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Compile kernel extension
        run: |
          make XCODE=OFF MACOS_VERSION_MIN="${VERSION_MIN}"
          make clean
          grep -q "SDKROOT = macosx;" *.xcodeproj/project.pbxproj
          sed -i.bak "s/SDKROOT = macosx;/SDKROOT = macosx${VERSION_MIN};/g" *.xcodeproj/project.pbxproj
          make XCODE=ON MACOS_VERSION_MIN="${VERSION_MIN}"

      - name: Make zipball from kext
        if: success() && env.IS_RELEASE == 'true'
        run: |
          cd ${{github.workspace}}/build/Release
          cp ${{github.workspace}}/other/check_cpuid.sh Install
          cp ${{github.workspace}}/other/uninstall Uninstall
          find Uninstall Install GoodbyeBigSlow.kext -type f \
          | sort \
          | zip --verbose --no-wild --symlinks -X --latest-time \
                --compression-method deflate -9 \
                -@ ${{github.workspace}}/GoodbyeBigSlow-${{github.ref_name}}.zip

      - name: Create GitHub release
        if: success() && env.IS_RELEASE == 'true'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: false
          replacesArtifacts: true
          artifacts: ${{github.workspace}}/GoodbyeBigSlow-${{github.ref_name}}.zip
          artifactContentType: raw
          tag: Downloads
          body: |
            **Changelog**: https://github.com/${{github.repository}}/commits/master

            **Installation**: Unpack the zip, click open `Install` and then follow the instructions.
          generateReleaseNotes: false
          omitNameDuringUpdate: false
          omitBodyDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          draft: false
          prerelease: false
